In [17]:
import numpy as np
import pandas as pd

# Datatype and Attributes

In [15]:
a1 = np.array([1, 2, 3])


a2 = np.array([
    [1, 2, 3],
    [1.1, 1.2, 1.3]
])



a3 = np.array([
    [[1, 2, 3],
    [4, 5, 6]],
    
    [[7, 8, 9],
    [1, 2, 3]]
])

In [13]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 2, 3))

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size    # total number of elemets

(3, 6, 12)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Converting ndarray to tables

In [20]:
df = pd.DataFrame(a2)    # restricted to 2D array. a1 -> series. a3 -> not possible
df

0    1    2
0  1.0  2.0  3.0
1  1.1  1.2  1.3

# Baisc Arrays

In [22]:
unitArray = np.ones((3,3), dtype = 'int32')    # default dtype is f64
unitArray

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
zeroArray = np.zeros((3,2), dtype = 'int32')
zeroArray

array([[0, 0],
       [0, 0],
       [0, 0]])

In [25]:
rangeArray = np.arange(0, 11, 2)
rangeArray

array([ 0,  2,  4,  6,  8, 10])

In [27]:
randomArray = np.random.randint(0, 10, (2,3))
randomArray

array([[4, 6, 4],
       [9, 4, 1]])

In [28]:
unityRandom = np.random.random((2,2))
unityRandom

array([[0.45154783, 0.23049417],
       [0.63230288, 0.1793765 ]])

In [32]:
np.random.seed(102)    # seed makes the output random, but uniform when recompiled
seededArray = np.random.randint(0, 10, (2,3))
seededArray

array([[0, 3, 2],
       [2, 2, 9]])

# Viewing arrays and matrices

In [33]:
np.unique(seededArray)

array([0, 2, 3, 9])

In [34]:
a3[0][0][0]

1

# Manipluating arrays

In [40]:
ones = np.ones(3, dtype = 'int32')
a1

array([1, 2, 3])

In [41]:
a1 + ones

array([2, 3, 4])

In [42]:
a1 - ones

array([0, 1, 2])

In [43]:
a1 * 2*ones

array([2, 4, 6])

In [46]:
a1 * a3
# Only possible if the mathematically possible

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 7, 16, 27],
        [ 1,  4,  9]]])

In [47]:
a1 / a3

array([[[1.        , 1.        , 1.        ],
        [0.25      , 0.4       , 0.5       ]],

       [[0.14285714, 0.25      , 0.33333333],
        [1.        , 1.        , 1.        ]]])

In [48]:
a1 // a3 # // means floor division -> div -> floor()

array([[[1, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 1]]], dtype=int32)

In [49]:
a1 ** 3

array([ 1,  8, 27], dtype=int32)

In [50]:
# raise to e
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
# take natural log
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [53]:
np.log10(a1)

array([0.        , 0.30103   , 0.47712125])

In [55]:
np.sum(a3)

51

In [56]:
np.mean(a3)

4.25

In [57]:
np.min(a3)

1

In [58]:
np.std(a3)

2.6180463454008347

In [59]:
np.var(a3)

6.854166666666667

# Standard Deviation and Variance

In [60]:
highVar = np.array([1, 100, 1000, 10000])
lowVar = np.array([1, 2, 3, 4])

In [63]:
np.var(highVar), np.var(lowVar)

(17550487.6875, 1.25)

In [64]:
np.std(highVar), np.std(lowVar)

(4189.330219438425, 1.118033988749895)